import { useRef, useState } from 'react';
import { SectionIndex } from '../components/SectionIndex';
import { SplitText } from '../components/SplitText';
import { useCanvas2D } from '../hooks/useCanvas2D';
import { useReveal } from '../hooks/useReveal';
import { useScrollProgress } from '../hooks/useScrollProgress';
import { SUPPRESSION } from '../data/nexera';
import { drawWorkflow } from './workflow/drawWorkflow';
import '../styles/workflow.css';

const STAGES = [
  {
    title: 'The eluent conducts',
    verb: 'Problem',
    text: 'Sodium carbonate pushes the anions through the column, but its own ions flood the conductivity cell. A few ppb of analyte disappear into a high, noisy baseline.',
  },
  {
    title: 'Membrane exchange',
    verb: 'Mechanism',
    text: 'In the electrodialytic suppressor, water electrolysis supplies a steady stream of H⁺. Cation-exchange membranes let H⁺ in and carry Na⁺ out. It regenerates continuously and needs no acid regenerant.',
  },
  {
    title: 'Background down, signal up',
    verb: 'Result',
    text: 'The eluent leaves as weakly conducting carbonic acid, while each analyte now travels with H⁺, which conducts far better than Na⁺. Detection limits drop from ppm toward ppb.',
  },
  {
    title: 'Cations: a different exchange',
    verb: 'ICDS-Ci',
    text: `Anion-exchange membranes bring OH⁻ in and carry methanesulfonate out, so the MSA eluent becomes water and each cation reaches the cell as its hydroxide. Sodium at 50 ppb: S/N ${SUPPRESSION.cationSN.before} → ${SUPPRESSION.cationSN.after.toLocaleString('en-US')}, about 30× better.`,
  },
];

export function Workflow() {
  const section = useRef<HTMLElement>(null);
  const progress = useRef(0);
  const [stage, setStage] = useState(0);
  const bars = useRef<(HTMLSpanElement | null)[]>([]);

  useReveal(section);
  useScrollProgress(section, (p) => {
    progress.current = p;
    const s = Math.min(3, Math.floor(p * 4));
    setStage((prev) => (prev === s ? prev : s));
    bars.current.forEach((b, i) => {
      if (b) b.style.transform = `scaleX(${Math.min(1, Math.max(0, p * 4 - i)).toFixed(3)})`;
    });
  });

  const canvas = useCanvas2D(({ ctx, w, h, t }) => drawWorkflow(ctx, w, h, t, progress.current));

  return (
    <section id="science" className="workflow" ref={section} aria-labelledby="workflow-title">
      <div className="workflow__sticky">
        <div className="container workflow__grid">
          <div className="workflow__text">
            <SectionIndex num="02" label="Suppression" />
            <SplitText as="h2" id="workflow-title" className="h-md workflow__title" text="Silence the background. Amplify the ion." />

            <div className="workflow__stage-num display" aria-hidden="true">
              <span key={stage}>0{stage + 1}</span>
            </div>

            <ol className="workflow__stages">
              {STAGES.map((s, i) => (
                <li key={s.title} className={`workflow-stage ${i === stage ? 'is-active' : ''}`} aria-current={i === stage ? 'step' : undefined}>
                  <div className="workflow-stage__head">
                    <span className="mono">{s.verb}</span>
                    <h3 className="h-sm">{s.title}</h3>
                  </div>
                  <p className="workflow-stage__text">{s.text}</p>
                  <span className="workflow-stage__bar" aria-hidden="true">
                    <span ref={(el) => (bars.current[i] = el)} />
                  </span>
                </li>
              ))}
            </ol>
          </div>

          <div className="workflow__viz">
            <canvas
              ref={canvas}
              className="workflow__canvas"
              role="img"
              aria-label="Animated diagram of suppressed conductivity: carbonate eluent ions crowd the conductivity cell; in the anion suppressor, cation-exchange membranes exchange sodium for hydrogen ions generated by water electrolysis and carbonate becomes carbonic acid; the baseline drops and analyte peaks grow. For cations, anion-exchange membranes bring in hydroxide and remove methanesulfonate so the eluent becomes water; sodium's signal-to-noise rises from 125 to 3,215."
            />
            <div className="workflow__frame" aria-hidden="true">
              <span />
              <span />
              <span />
              <span />
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
